import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LocalFont from "@next/font/local";
import {ReactNode} from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const calSans = LocalFont({
  src: "../../public/CalSans-SemiBold.ttf",
  variable: "--font-calsans",
});

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" className={[inter.variable, calSans.variable].join(" ")}>
    <body
        className={`bg-black ${
            process.env.NODE_ENV === "development" ? "debug-screens" : undefined
        }`}
    >
    {children}
    </body>
    </html>
  )
}
